name: First Workflow

on:
  push:
    branches:
      - workflow-branch

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          python -v
          python -m pip -v
